---
name: Get PR Status

on:
  workflow_call:
    inputs:
      runner:
        description: "GitHub Runner"
        required: true
        type: string
    outputs:
      draft_state:
        description: "Show if the PR is in draft or not"
        value: ${{ jobs.get_pr_status.outputs.draft_state }}
      mergeable:
        description: "Show if the PR can be merged or not"
        value: ${{ jobs.get_pr_status.outputs.mergeable }}

jobs:
  get_pr_status:
    name: Get PR Status
    runs-on: ${{ inputs.runner }}
    outputs:
      mergeable: ${{ steps.pr_status.outputs.mergeable }}
      draft_state: ${{ steps.pr_status.outputs.draft_state }}

    steps:
      - name: Get PR Status
        id: pr_status
        uses: actions/github-script@v7
        with:
          script: |
            let mergeable = "false";
            let draftState = core.getInput('is-draft') === "false" ? "false" : "true";
            let reviewState = core.getInput('review-state') === "approved" ? "approved" : "not approved";

            if (draftState === "false" && reviewState === "approved") {
              mergeable = "true";
            }

            console.log(`Pull request:`);
            console.log(`\t- is a draft: ${draftState}`);
            console.log(`\t- was ${reviewState}`);
            console.log(`\t- was labeled with merge: ${mergeable}`);
            console.log(`\t- is mergeable: ${mergeable}`);

            core.setOutput("mergeable", mergeable);
            core.setOutput("draft_state", draftState);
          is-draft: ${{ github.event.pull_request.draft }}
          review-state: ${{ github.event.review.state }}
