name: Manage Pull Requests

on:
  workflow_call:
    inputs:
      runner:
        description: "GitHub Runner"
        required: true
        type: string
      merge_method:
        description: "Merge method"
        required: false
        type: string
        default: "merge"

jobs:
  get_pr_status:
    needs: get_pr_status
    uses: arghpy/shared-workflows/.github/workflows/get_pr_status.yaml@break_the_other_jobs
    secrets: inherit
    with:
      runner: ${{ inputs.runner }}

  lint_changed_files:
    needs: get_pr_status
    if: |
      needs.get_pr_status.outputs.draft_state == 'false' &&
      needs.get_pr_status.outputs.mergeable == 'false'
    uses: arghpy/shared-workflows/.github/workflows/lint.yaml@break_the_other_jobs
    secrets: inherit
    with:
      runner: ${{ inputs.runner }}

  auto_merge:
    needs: [lint_changed_files, get_pr_status, auto_merge_optional]
    if: |
      always() &&
      needs.get_pr_status.result == 'success' &&
      needs.get_pr_status.outputs.mergeable == 'true' &&
      (needs.lint_changed_files.result == 'success' || needs.lint_changed_files.result == 'skipped') &&
      (needs.auto_merge_optional.result == 'success' || needs.auto_merge_optional.result == 'skipped')
    uses: arghpy/shared-workflows/.github/workflows/auto_merge.yaml@break_the_other_jobs
    secrets: inherit
    with:
      runner: ${{ inputs.runner }}
      merge_method: ${{ inputs.merge_method }}
